"""文档树构建与向量化入库。"""

from __future__ import annotations

import uuid
from datetime import datetime, timezone
from typing import Iterable, Literal, Sequence

import numpy as np

from src.config.embedding import EmbeddingModel
from src.config.indexing_config import DOCUMENT_SUMMARY_MAX_CHARS
from src.parsing.document_payload_builder import text_to_payload
from src.parsing.document_types import (
    DocumentPayload,
    NodeKind,
    ParagraphPayload,
    SectionPayload,
    SentencePayload,
    StoredNode,
    TreeNode,
)
from src.parsing.text_splitter import (
    build_document_summary,
    split_paragraphs,
    split_sentences,
)
from src.config.logging_config import get_logger
from src.storage.milvus_rag_node_store import MilvusPostgresNodeStore

logger = get_logger(__name__)

ParagraphEmbeddingMode = Literal["averaged", "full", "both"]


def _count_by_kind(nodes: Iterable[TreeNode]) -> dict[str, int]:
    counts: dict[str, int] = {}
    for node in nodes:
        key = node.kind.value
        counts[key] = counts.get(key, 0) + 1
    return counts


def _sentence_payloads_from_text(text: str) -> list[SentencePayload]:
    return [SentencePayload(text=s) for s in split_sentences(text)]


def _paragraph_payload_from_text(text: str) -> ParagraphPayload:
    return ParagraphPayload(
        text=text,
        sentences=_sentence_payloads_from_text(text),
    )


def _sections_from_text(document: DocumentPayload) -> list[SectionPayload]:
    paragraphs = [
        _paragraph_payload_from_text(paragraph)
        for paragraph in split_paragraphs(document.text)
    ]
    return [
        SectionPayload(
            title=document.title,
            paragraphs=paragraphs,
            metadata={"autogenerated": True},
        )
    ]


class DocumentTreeBuilder:
    def build_tree(self, document: DocumentPayload) -> TreeNode:
        counters = {"section": 0, "paragraph": 0, "sentence": 0}
        sections = document.sections or _sections_from_text(document)
        document_text = document.text or "\n\n".join(
            paragraph.text
            for section in sections
            for paragraph in section.paragraphs
        )

        root_metadata = dict(document.metadata)
        root_metadata.setdefault("document_id", document.document_id)
        root_metadata.setdefault("document_title", document.title)
        root_metadata["total_chars"] = len(document_text)
        root_metadata["text_is_summary"] = True
        document_summary = build_document_summary(
            document.title,
            document_text,
            max_chars=DOCUMENT_SUMMARY_MAX_CHARS,
        )
        root = TreeNode(
            node_id=document.document_id,
            parent_id=None,
            kind=NodeKind.DOCUMENT,
            title=document.title,
            text=document_summary,
            metadata=root_metadata,
        )

        for section in sections:
            counters["section"] += 1
            section_id = f"{document.document_id}:sec{counters['section']}"
            section_meta = dict(section.metadata)
            section_meta.update(
                {
                    "document_id": document.document_id,
                    "document_title": document.title,
                    "section_index": counters["section"],
                }
            )
            section_node = TreeNode(
                node_id=section_id,
                parent_id=root.node_id,
                kind=NodeKind.SECTION,
                title=section.title,
                text=section.title,
                metadata=section_meta,
            )
            root.children.append(section_node)

            for paragraph in section.paragraphs:
                counters["paragraph"] += 1
                paragraph_id = f"{section_id}:p{counters['paragraph']}"
                paragraph_meta = dict(paragraph.metadata)
                paragraph_meta.update(
                    {
                        "document_id": document.document_id,
                        "document_title": document.title,
                        "section_id": section_id,
                        "section_index": counters["section"],
                        "paragraph_index": counters["paragraph"],
                    }
                )
                paragraph_node = TreeNode(
                    node_id=paragraph_id,
                    parent_id=section_id,
                    kind=NodeKind.PARAGRAPH,
                    title=section.title,
                    text=paragraph.text,
                    metadata=paragraph_meta,
                )
                section_node.children.append(paragraph_node)

                sentences = paragraph.sentences or _sentence_payloads_from_text(
                    paragraph.text
                )
                for sentence in sentences:
                    counters["sentence"] += 1
                    sentence_id = f"{paragraph_id}:s{counters['sentence']}"
                    sentence_meta = dict(sentence.metadata)
                    sentence_meta.update(
                        {
                            "document_id": document.document_id,
                            "document_title": document.title,
                            "section_id": section_id,
                            "paragraph_id": paragraph_id,
                            "sentence_index": counters["sentence"],
                        }
                    )
                    sentence_node = TreeNode(
                        node_id=sentence_id,
                        parent_id=paragraph_id,
                        kind=NodeKind.SENTENCE,
                        title=section.title,
                        text=sentence.text,
                        metadata=sentence_meta,
                    )
                    paragraph_node.children.append(sentence_node)

        return root

    def flatten(self, node: TreeNode) -> Iterable[TreeNode]:
        yield node
        for child in node.children:
            yield from self.flatten(child)


def _normalize_vectors(vectors: np.ndarray) -> np.ndarray:
    norms = np.linalg.norm(vectors, axis=1, keepdims=True)
    norms[norms == 0] = 1.0
    return vectors / norms


def average_embeddings(child_vectors: Sequence[np.ndarray]) -> np.ndarray:
    if not child_vectors:
        raise ValueError("average_embeddings requires at least one child vector.")
    stacked = np.vstack(child_vectors)
    return _normalize_vectors(np.mean(stacked, axis=0, keepdims=True))[0]


def documents_from_payload(payload: DocumentPayload) -> list[dict]:
    tree_indexer = DocumentTreeBuilder()
    root = tree_indexer.build_tree(payload)
    docs: list[dict] = []
    for node in tree_indexer.flatten(root):
        if node.kind == NodeKind.DOCUMENT:
            continue
        metadata = dict(node.metadata)
        metadata["node_id"] = node.node_id
        metadata["node_kind"] = node.kind.value
        metadata["node_title"] = node.title
        if node.parent_id is not None:
            metadata["parent_id"] = node.parent_id
        docs.append({"text": node.text, "metadata": metadata})
    return docs


class DocumentIndexer:
    def __init__(
        self,
        embedding_model: EmbeddingModel,
        datastore: MilvusPostgresNodeStore,
        paragraph_embedding_mode: ParagraphEmbeddingMode = "averaged",
    ) -> None:
        self._embedding_model = embedding_model
        self._datastore = datastore
        self._paragraph_embedding_mode = paragraph_embedding_mode
        self._tree_indexer = DocumentTreeBuilder()

    async def index_text(
        self,
        text: str,
        *,
        document_id: str | None = None,
        title: str = "Untitled",
        metadata: dict | None = None,
    ) -> list[StoredNode]:
        payload = text_to_payload(
            document_id=document_id or str(uuid.uuid4()),
            title=title,
            text=text,
            metadata=dict(metadata or {}),
        )
        return await self.index_document(payload)

    async def index_document(self, document: DocumentPayload) -> list[StoredNode]:
        text_len = len(document.text or "")
        logger.info(
            "index_document start doc_id=%s title=%s text_len=%s summary_max=%s paragraph_mode=%s",
            document.document_id,
            document.title,
            text_len,
            DOCUMENT_SUMMARY_MAX_CHARS,
            self._paragraph_embedding_mode,
        )
        root = self._tree_indexer.build_tree(document)
        flat_nodes = list(self._tree_indexer.flatten(root))
        kind_counts = _count_by_kind(flat_nodes)
        logger.info(
            "index_document step 1/4 tree_built nodes=%s kinds=%s",
            len(flat_nodes),
            kind_counts,
        )
        await self._embed_tree(root)

        now_ts = int(datetime.now(timezone.utc).timestamp())
        stored_nodes = [
            self._to_stored(node, created_at=now_ts)
            for node in flat_nodes
        ]
        searchable = sum(
            1
            for node in stored_nodes
            if node.kind in {NodeKind.SENTENCE, NodeKind.PARAGRAPH}
        )
        logger.info(
            "index_document step 3/4 persist start nodes=%s searchable=%s",
            len(stored_nodes),
            searchable,
        )
        await self._datastore.upsert_nodes(stored_nodes)
        await self._datastore.upsert_bm25_entries(stored_nodes)
        logger.info(
            "index_document step 4/4 done doc_id=%s nodes=%s kinds=%s searchable=%s",
            document.document_id,
            len(stored_nodes),
            kind_counts,
            searchable,
        )
        return stored_nodes

    async def _embed_tree(self, root: TreeNode) -> None:
        leaves = [node for node in self._tree_indexer.flatten(root) if not node.children]
        if leaves:
            leaf_chars = sum(len(leaf.text) for leaf in leaves)
            logger.info(
                "index_document step 2/4 embed_leaves count=%s chars=%s",
                len(leaves),
                leaf_chars,
            )
            embeddings = await self._embedding_model.embed_text(
                [leaf.text for leaf in leaves]
            )
            for leaf, vector in zip(leaves, embeddings, strict=True):
                leaf.embedding = vector

        paragraphs = [
            node
            for node in self._tree_indexer.flatten(root)
            if node.kind == NodeKind.PARAGRAPH
        ]
        para_full_map: dict[str, np.ndarray] = {}
        if self._paragraph_embedding_mode in ("full", "both") and paragraphs:
            para_chars = sum(len(p.text) for p in paragraphs)
            logger.info(
                "index_document step 2/4 embed_paragraph_full count=%s chars=%s mode=%s",
                len(paragraphs),
                para_chars,
                self._paragraph_embedding_mode,
            )
            para_embeddings = await self._embedding_model.embed_text(
                [p.text for p in paragraphs]
            )
            para_full_map = {
                p.node_id: vec for p, vec in zip(paragraphs, para_embeddings, strict=True)
            }

        self._propagate_embeddings(root, para_full_map)
        logger.info("index_document step 2/4 embed_done dim=%s", self._embedding_model.dimension)

    def _propagate_embeddings(
        self,
        node: TreeNode,
        para_full_map: dict[str, np.ndarray] | None = None,
    ) -> np.ndarray:
        if para_full_map is None:
            para_full_map = {}
        if node.embedding is not None:
            return node.embedding

        child_vectors = [
            self._propagate_embeddings(child, para_full_map) for child in node.children
        ]
        if not child_vectors:
            raise ValueError(f"Node {node.node_id} is missing an embedding.")

        averaged_embedding = average_embeddings(child_vectors)
        if node.kind == NodeKind.PARAGRAPH and node.node_id in para_full_map:
            full_embedding = para_full_map[node.node_id]
            if self._paragraph_embedding_mode == "full":
                node.embedding = full_embedding
            elif self._paragraph_embedding_mode == "both":
                node.embedding = averaged_embedding
                node.metadata["full_embedding"] = full_embedding.tobytes().hex()
            else:
                node.embedding = averaged_embedding
        else:
            node.embedding = averaged_embedding
        return node.embedding

    def _to_stored(self, node: TreeNode, *, created_at: int = 0) -> StoredNode:
        if node.embedding is None:
            raise ValueError(f"Node {node.node_id} is missing an embedding.")
        embedding = node.embedding
        if hasattr(embedding, "tolist"):
            embedding = embedding.tolist()
        return StoredNode(
            node_id=node.node_id,
            parent_id=node.parent_id,
            kind=node.kind,
            title=node.title,
            text=node.text,
            metadata=node.metadata,
            embedding=embedding,
            child_ids=[child.node_id for child in node.children],
            created_at=created_at,
        )
