"""Convert uploaded files into structured DocumentPayloads."""

from dataclasses import asdict
from pathlib import Path
from typing import Any

from .document_types import DocumentPayload, ParagraphPayload, SectionPayload, SentencePayload
from .markitdown_reader import convert_path_to_markdown
from .markdown_parser import parse_markdown_sections
from .text_splitter import split_paragraphs, split_sentences

TXT_EXTS = {".txt"}


def text_to_payload(
    *,
    document_id: str,
    title: str,
    text: str,
    metadata: dict[str, Any],
) -> DocumentPayload:
    paragraphs = [
        ParagraphPayload(
            text=paragraph,
            sentences=[
                SentencePayload(text=sentence)
                for sentence in split_sentences(paragraph)
            ],
        )
        for paragraph in split_paragraphs(text)
    ]
    sections = [
        SectionPayload(
            title=title,
            paragraphs=paragraphs,
            metadata={"autogenerated": True},
        )
    ]
    return DocumentPayload(
        document_id=document_id,
        title=title,
        text=text,
        metadata=metadata,
        sections=sections,
    )


def markdown_to_payload(
    *,
    document_id: str,
    title: str,
    markdown_text: str,
    metadata: dict[str, Any],
) -> DocumentPayload:
    sections = parse_markdown_sections(markdown_text, default_title=title)
    if not sections:
        sections = text_to_payload(
            document_id=document_id,
            title=title,
            text=markdown_text,
            metadata=metadata,
        ).sections or []

    return DocumentPayload(
        document_id=document_id,
        title=title,
        text=markdown_text,
        metadata=metadata,
        sections=sections,
    )


def payload_to_dict(payload: DocumentPayload) -> dict:
    return asdict(payload)


def dict_to_payload(data: dict[str, Any]) -> DocumentPayload:
    sections_data = data.get("sections") or []
    sections: list[SectionPayload] = []

    for section in sections_data:
        paragraphs: list[ParagraphPayload] = []

        for paragraph in section.get("paragraphs", []):
            sentences = [
                SentencePayload(
                    text=sentence.get("text", ""),
                    metadata=sentence.get("metadata", {}),
                )
                for sentence in paragraph.get("sentences", []) or []
            ]

            paragraphs.append(
                ParagraphPayload(
                    text=paragraph.get("text", ""),
                    sentences=sentences or None,
                    metadata=paragraph.get("metadata", {}),
                )
            )

        sections.append(
            SectionPayload(
                title=section.get("title", ""),
                paragraphs=paragraphs,
                metadata=section.get("metadata", {}),
            )
        )

    return DocumentPayload(
        document_id=data["document_id"],
        title=data.get("title", data["document_id"]),
        text=data.get("text", ""),
        metadata=data.get("metadata", {}),
        sections=sections or None,
    )


def parse_document_path(
    path: Path,
    *,
    doc_id: str | None = None,
    title: str | None = None,
    metadata: dict[str, Any] | None = None,
) -> DocumentPayload:
    """解析本地文件：.txt 直读；其余格式 MarkItDown → markdown_parser。"""
    payload_metadata = dict(metadata or {})
    resolved = path.resolve()
    ext = resolved.suffix.lower()
    payload_metadata.setdefault("source_path", str(resolved))
    payload_metadata.setdefault("source_filename", resolved.name)
    payload_metadata.setdefault("source_format", ext.lstrip("."))

    document_id = doc_id or resolved.stem
    document_title = title or document_id

    if ext in TXT_EXTS:
        text = resolved.read_text(encoding="utf-8", errors="replace")
        return text_to_payload(
            document_id=document_id,
            title=document_title,
            text=text,
            metadata=payload_metadata,
        )

    markdown_text = convert_path_to_markdown(resolved)
    payload_metadata["converted_via"] = "markitdown"
    return markdown_to_payload(
        document_id=document_id,
        title=document_title,
        markdown_text=markdown_text,
        metadata=payload_metadata,
    )
