"""Structured Markdown → section/paragraph payloads for RAG indexing."""

from __future__ import annotations

import re
from typing import Any

from .document_types import ParagraphPayload, SectionPayload, SentencePayload
from .text_splitter import split_sentences

HEADING_RE = re.compile(r"^(#{1,6})\s+(.*)$")
LIST_ITEM_RE = re.compile(r"^(\s*)([-*+]|\d+\.)\s+(.+)$")
HR_RE = re.compile(r"^(-{3,}|\*{3,}|_{3,})\s*$")
TABLE_SEPARATOR_RE = re.compile(
    r"^\s*\|?(?:\s*:?-{3,}:?\s*\|)+\s*:?-{3,}:?\s*\|?\s*$"
)
FENCE_RE = re.compile(r"^(`{3,}|~{3,})(.*)$")


def _normalize_newlines(text: str) -> str:
    return text.replace("\r\n", "\n").replace("\r", "\n")


def _normalize_cell(cell: str) -> str:
    """Unescape common MarkItDown / Excel export literals in table cells."""
    return (
        cell.replace("\\n", "\n")
        .replace("\\t", "\t")
        .replace("\\|", "|")
        .strip()
    )


def _is_table_line(line: str) -> bool:
    stripped = line.strip()
    if not stripped:
        return False
    if TABLE_SEPARATOR_RE.match(stripped):
        return True
    return "|" in stripped and stripped.count("|") >= 2


def _parse_table_cells(line: str) -> list[str]:
    stripped = line.strip()
    if stripped.startswith("|"):
        stripped = stripped[1:]
    if stripped.endswith("|"):
        stripped = stripped[:-1]
    return [_normalize_cell(cell) for cell in stripped.split("|")]


def _format_table_row(headers: list[str], cells: list[str]) -> str:
    """按表头原样拼接行文本，仅做拆分，不改写列名或单元格内容。"""
    if not headers:
        return " | ".join(cells)

    lines: list[str] = []
    for idx, cell in enumerate(cells):
        if not cell:
            continue
        if idx < len(headers) and headers[idx]:
            lines.append(f"{headers[idx]}: {cell}")
        else:
            lines.append(cell)
    return "\n".join(lines)


def _paragraph_from_text(
    text: str,
    *,
    metadata: dict[str, Any] | None = None,
    atomic: bool = False,
) -> ParagraphPayload:
    text = text.strip()
    meta = dict(metadata or {})
    block_type = meta.get("block_type", "paragraph")
    if atomic or block_type in {"code", "table_row"}:
        sentences = [SentencePayload(text=text)] if text else []
    else:
        sentences = [SentencePayload(text=s) for s in split_sentences(text)]
    return ParagraphPayload(text=text, sentences=sentences or None, metadata=meta)


def _parse_table_block(table_lines: list[str]) -> list[ParagraphPayload]:
    if not table_lines:
        return []

    header: list[str] | None = None
    data_rows: list[list[str]] = []
    for line in table_lines:
        stripped = line.strip()
        if not stripped or TABLE_SEPARATOR_RE.match(stripped):
            continue
        cells = _parse_table_cells(line)
        if not any(cells):
            continue
        if header is None:
            header = cells
            continue
        data_rows.append(cells)

    paragraphs: list[ParagraphPayload] = []
    for row_index, cells in enumerate(data_rows, start=1):
        row_text = _format_table_row(header or [], cells)
        if not row_text.strip():
            continue
        paragraphs.append(
            _paragraph_from_text(
                row_text,
                metadata={
                    "block_type": "table_row",
                    "row_index": row_index,
                    "column_count": len(cells),
                    "table_headers": header or [],
                },
                atomic=True,
            )
        )
    return paragraphs


def parse_markdown_sections(
    markdown_text: str,
    *,
    default_title: str,
) -> list[SectionPayload]:
    """Parse Markdown into hierarchical sections with RAG-friendly paragraphs."""
    text = _normalize_newlines(markdown_text)
    lines = text.split("\n")

    sections: list[SectionPayload] = []
    current_title = default_title
    current_section_meta: dict[str, Any] = {"autogenerated": False}
    paragraphs: list[ParagraphPayload] = []
    prose_buffer: list[str] = []

    def flush_prose() -> None:
        if not prose_buffer:
            return
        paragraph_text = "\n".join(prose_buffer).strip()
        prose_buffer.clear()
        if paragraph_text:
            paragraphs.append(
                _paragraph_from_text(
                    paragraph_text,
                    metadata={"block_type": "paragraph"},
                )
            )

    def flush_section() -> None:
        nonlocal paragraphs
        flush_prose()
        if paragraphs:
            sections.append(
                SectionPayload(
                    title=current_title,
                    paragraphs=list(paragraphs),
                    metadata=dict(current_section_meta),
                )
            )
            paragraphs = []

    index = 0
    while index < len(lines):
        line = lines[index]

        heading_match = HEADING_RE.match(line)
        if heading_match:
            flush_section()
            current_title = heading_match.group(2).strip() or default_title
            current_section_meta = {
                "autogenerated": False,
                "level": len(heading_match.group(1)),
            }
            index += 1
            continue

        fence_match = FENCE_RE.match(line.strip())
        if fence_match:
            flush_prose()
            fence = fence_match.group(1)
            language = (fence_match.group(2) or "").strip()
            index += 1
            code_lines: list[str] = []
            while index < len(lines):
                if lines[index].strip().startswith(fence[0] * len(fence)):
                    break
                code_lines.append(lines[index])
                index += 1
            if index < len(lines):
                index += 1
            code_text = "\n".join(code_lines).strip()
            if code_text:
                paragraphs.append(
                    _paragraph_from_text(
                        code_text,
                        metadata={
                            "block_type": "code",
                            "language": language or None,
                        },
                        atomic=True,
                    )
                )
            continue

        if _is_table_line(line):
            flush_prose()
            table_lines: list[str] = []
            while index < len(lines) and _is_table_line(lines[index]):
                table_lines.append(lines[index])
                index += 1
            paragraphs.extend(_parse_table_block(table_lines))
            continue

        list_match = LIST_ITEM_RE.match(line)
        if list_match:
            flush_prose()
            while index < len(lines):
                item_match = LIST_ITEM_RE.match(lines[index])
                if not item_match:
                    break
                item_text = item_match.group(3).strip()
                if item_text:
                    paragraphs.append(
                        _paragraph_from_text(
                            item_text,
                            metadata={
                                "block_type": "list_item",
                                "list_marker": item_match.group(2),
                            },
                        )
                    )
                index += 1
            continue

        if line.strip().startswith(">"):
            flush_prose()
            quote_lines: list[str] = []
            while index < len(lines) and lines[index].strip().startswith(">"):
                quote_lines.append(lines[index].strip().lstrip(">").strip())
                index += 1
            quote_text = "\n".join(quote_lines).strip()
            if quote_text:
                paragraphs.append(
                    _paragraph_from_text(
                        quote_text,
                        metadata={"block_type": "blockquote"},
                    )
                )
            continue

        if HR_RE.match(line.strip()):
            flush_prose()
            index += 1
            continue

        if not line.strip():
            flush_prose()
            index += 1
            continue

        prose_buffer.append(line)
        index += 1

    flush_section()

    if not sections:
        sections.append(
            SectionPayload(
                title=default_title,
                paragraphs=[
                    _paragraph_from_text(
                        text.strip(),
                        metadata={"block_type": "paragraph", "autogenerated": True},
                    )
                ],
                metadata={"autogenerated": True},
            )
        )

    return sections
