"""Build a hierarchical tree from DocumentPayload."""

from typing import Iterable

from .text_utils import split_paragraphs, split_sentences
from .types import (
    DocumentPayload,
    NodeKind,
    ParagraphPayload,
    SectionPayload,
    SentencePayload,
    TreeNode,
)


def sentence_payloads_from_text(text: str) -> list[SentencePayload]:
    return [SentencePayload(text=s) for s in split_sentences(text)]


def paragraph_payload_from_text(text: str) -> ParagraphPayload:
    return ParagraphPayload(
        text=text,
        sentences=sentence_payloads_from_text(text),
    )


def sections_from_text(document: DocumentPayload) -> list[SectionPayload]:
    paragraphs = [
        paragraph_payload_from_text(paragraph)
        for paragraph in split_paragraphs(document.text)
    ]
    return [
        SectionPayload(
            title=document.title,
            paragraphs=paragraphs,
            metadata={"autogenerated": True},
        )
    ]


class DocumentIndexer:
    def build_tree(self, document: DocumentPayload) -> TreeNode:
        return self._build_tree(document)

    def _build_tree(self, document: DocumentPayload) -> TreeNode:
        counters = {"section": 0, "paragraph": 0, "sentence": 0}
        sections = document.sections or sections_from_text(document)

        document_text = document.text or "\n\n".join(
            paragraph.text
            for section in sections
            for paragraph in section.paragraphs
        )

        root_metadata = dict(document.metadata)
        root_metadata.setdefault("document_id", document.document_id)
        root_metadata.setdefault("document_title", document.title)
        root = TreeNode(
            node_id=document.document_id,
            parent_id=None,
            kind=NodeKind.DOCUMENT,
            title=document.title,
            text=document_text,
            metadata=root_metadata,
        )

        for section in sections:
            counters["section"] += 1
            section_id = f"{document.document_id}:sec{counters['section']}"
            section_meta = dict(section.metadata)
            section_meta.update(
                {
                    "document_id": document.document_id,
                    "document_title": document.title,
                    "section_index": counters["section"],
                }
            )
            section_node = TreeNode(
                node_id=section_id,
                parent_id=root.node_id,
                kind=NodeKind.SECTION,
                title=section.title,
                text=section.title,
                metadata=section_meta,
            )
            root.children.append(section_node)

            for paragraph in section.paragraphs:
                counters["paragraph"] += 1
                paragraph_id = f"{section_id}:p{counters['paragraph']}"
                paragraph_meta = dict(paragraph.metadata)
                paragraph_meta.update(
                    {
                        "document_id": document.document_id,
                        "document_title": document.title,
                        "section_id": section_id,
                        "section_index": counters["section"],
                        "paragraph_index": counters["paragraph"],
                    }
                )
                paragraph_node = TreeNode(
                    node_id=paragraph_id,
                    parent_id=section_id,
                    kind=NodeKind.PARAGRAPH,
                    title=section.title,
                    text=paragraph.text,
                    metadata=paragraph_meta,
                )
                section_node.children.append(paragraph_node)

                sentences = paragraph.sentences or sentence_payloads_from_text(
                    paragraph.text
                )
                for sentence in sentences:
                    counters["sentence"] += 1
                    sentence_id = f"{paragraph_id}:s{counters['sentence']}"
                    sentence_meta = dict(sentence.metadata)
                    sentence_meta.update(
                        {
                            "document_id": document.document_id,
                            "document_title": document.title,
                            "section_id": section_id,
                            "paragraph_id": paragraph_id,
                            "sentence_index": counters["sentence"],
                        }
                    )
                    sentence_node = TreeNode(
                        node_id=sentence_id,
                        parent_id=paragraph_id,
                        kind=NodeKind.SENTENCE,
                        title=section.title,
                        text=sentence.text,
                        metadata=sentence_meta,
                    )
                    paragraph_node.children.append(sentence_node)

        return root

    def flatten(self, node: TreeNode) -> Iterable[TreeNode]:
        yield node
        for child in node.children:
            yield from self.flatten(child)
