"""Convert PDF/Markdown/Text into structured DocumentPayloads."""

import re
from dataclasses import asdict
from pathlib import Path
from typing import Any

from .pdf_utils import pdf_to_document_payload
from .text_utils import split_paragraphs, split_sentences
from .types import DocumentPayload, ParagraphPayload, SectionPayload, SentencePayload

HEADING_RE = re.compile(r"^(#{1,6})\s+(.*)$")
MARKDOWN_EXTS = {".md", ".markdown"}


def text_to_payload(
    *,
    document_id: str,
    title: str,
    text: str,
    metadata: dict[str, Any],
) -> DocumentPayload:
    paragraphs = [
        ParagraphPayload(
            text=paragraph,
            sentences=[
                SentencePayload(text=sentence)
                for sentence in split_sentences(paragraph)
            ],
        )
        for paragraph in split_paragraphs(text)
    ]
    sections = [
        SectionPayload(
            title=title,
            paragraphs=paragraphs,
            metadata={"autogenerated": True},
        )
    ]
    return DocumentPayload(
        document_id=document_id,
        title=title,
        text=text,
        metadata=metadata,
        sections=sections,
    )


def markdown_to_payload(
    *,
    document_id: str,
    title: str,
    markdown_text: str,
    metadata: dict[str, Any],
) -> DocumentPayload:
    sections: list[SectionPayload] = []
    current_paragraph_lines: list[str] = []
    current_title = title
    current_metadata: dict[str, Any] = {}
    section_paragraphs: list[ParagraphPayload] = []

    def flush_paragraph() -> None:
        if not current_paragraph_lines:
            return

        paragraph_text = "\n".join(current_paragraph_lines).strip()
        current_paragraph_lines.clear()

        sentences = [
            SentencePayload(text=sentence)
            for sentence in split_sentences(paragraph_text)
        ]
        section_paragraphs.append(
            ParagraphPayload(
                text=paragraph_text,
                sentences=sentences,
            )
        )

    def flush_section() -> None:
        if section_paragraphs:
            sections.append(
                SectionPayload(
                    title=current_title,
                    paragraphs=list(section_paragraphs),
                    metadata=dict(current_metadata),
                )
            )
            section_paragraphs.clear()

    for line in markdown_text.splitlines():
        heading_match = HEADING_RE.match(line)

        if heading_match:
            flush_paragraph()
            flush_section()
            current_title = heading_match.group(2).strip()
            current_metadata = {"level": len(heading_match.group(1))}
            continue

        if not line.strip():
            flush_paragraph()
            continue

        current_paragraph_lines.append(line)

    flush_paragraph()
    flush_section()

    if not sections:
        sections = (
            text_to_payload(
                document_id=document_id,
                title=title,
                text=markdown_text,
                metadata=metadata,
            ).sections
            or []
        )

    return DocumentPayload(
        document_id=document_id,
        title=title,
        text=markdown_text,
        metadata=metadata,
        sections=sections,
    )


def payload_to_dict(payload: DocumentPayload) -> dict:
    return asdict(payload)


def dict_to_payload(data: dict[str, Any]) -> DocumentPayload:
    sections_data = data.get("sections") or []
    sections: list[SectionPayload] = []

    for section in sections_data:
        paragraphs: list[ParagraphPayload] = []

        for paragraph in section.get("paragraphs", []):
            sentences = [
                SentencePayload(
                    text=sentence.get("text", ""),
                    metadata=sentence.get("metadata", {}),
                )
                for sentence in paragraph.get("sentences", []) or []
            ]

            paragraphs.append(
                ParagraphPayload(
                    text=paragraph.get("text", ""),
                    sentences=sentences or None,
                    metadata=paragraph.get("metadata", {}),
                )
            )

        sections.append(
            SectionPayload(
                title=section.get("title", ""),
                paragraphs=paragraphs,
                metadata=section.get("metadata", {}),
            )
        )

    return DocumentPayload(
        document_id=data["document_id"],
        title=data.get("title", data["document_id"]),
        text=data.get("text", ""),
        metadata=data.get("metadata", {}),
        sections=sections or None,
    )


def parse_document_path(
    path: Path,
    *,
    doc_id: str | None = None,
    title: str | None = None,
    metadata: dict[str, Any] | None = None,
) -> DocumentPayload:
    payload_metadata = dict(metadata or {})
    resolved = path.resolve()
    ext = resolved.suffix.lower()
    payload_metadata.setdefault("source_path", str(resolved))
    payload_metadata.setdefault("source_filename", resolved.name)
    payload_metadata.setdefault("source_format", ext.lstrip("."))

    document_id = doc_id or resolved.stem
    document_title = title or document_id

    if ext == ".pdf":
        return pdf_to_document_payload(
            resolved,
            doc_id=document_id,
            title=document_title,
            metadata=payload_metadata,
        )

    text = resolved.read_text(encoding="utf-8", errors="replace")
    if ext in MARKDOWN_EXTS:
        return markdown_to_payload(
            document_id=document_id,
            title=document_title,
            markdown_text=text,
            metadata=payload_metadata,
        )

    return text_to_payload(
        document_id=document_id,
        title=document_title,
        text=text,
        metadata=payload_metadata,
    )
